GET http://localhost:3001/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImZWUHpIdmk3OElMdFRXYTYiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzE3OTA5NzIyLCJpYXQiOjE3MTczMDQ5MjIsImlzcyI6Imh0dHBzOi8vdWZzc2J6ZnFkbG92aG90bG1oamYuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjUwY2Y2NTYyLTEyOTYtNDhlOS04YTFiLTZlMjBlNTE0MTVhNSIsImVtYWlsIjoicml6a3ltYXVsYW5hODIwOEBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoicml6a3ltYXVsYW5hODIwOEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNTBjZjY1NjItMTI5Ni00OGU5LThhMWItNmUyMGU1MTQxNWE1In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MTczMDQ5MjJ9XSwic2Vzc2lvbl9pZCI6IjQ2NGMxNzlmLTczZTItNDk0My05YmZlLTIwZGJmMTU3YTMzNCIsImlzX2Fub255bW91cyI6ZmFsc2V9.XALyNDZw9WSPZnwoqu-GIvoQHWxnin-gtH-MssgPupc